/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dll_tm_TradeMarkDll */

#ifndef _Included_com_dll_tm_TradeMarkDll
#define _Included_com_dll_tm_TradeMarkDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dll_tm_TradeMarkDll
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dll_tm_TradeMarkDll_init
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_dll_tm_TradeMarkDll
 * Method:    search
 * Signature: (Ljava/lang/String;Ljava/lang/String;F)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dll_tm_TradeMarkDll_search
  (JNIEnv *, jclass, jstring, jstring, jfloat);
  
JNIEXPORT jstring JNICALL Java_com_dll_tm_TradeMarkDll_search_multiThread
  (JNIEnv *, jclass, jstring, jstring, jfloat, jint);

/*
 * Class:     com_dll_tm_TradeMarkDll
 * Method:    buildFeature
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dll_tm_TradeMarkDll_buildFeature
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
